### ISSUE TITLE
undefined: NewClient

### ISSUE THREAD

**Issue by kavwang** [krylovsk/influxdb-benchmark#1]
Thank for your script, but I faced some problem when using 0.13 influxdb. Can you fix that?

`
$ go build main.go
# command-line-arguments

./main.go:104: undefined: NewClient
`

**Comment by krylovsk** [comment]
Thanks for reporting this. The InfluxDB API has changed since 0.9 when this tool was implemented, but it's quite easy to fix.

**Comment by kavwang** [comment]
Thank @krylovsk  for the commit, but main.go:105 still used the old API.

**Comment by krylovsk** [comment]
The main.go:105 calls client.go:24. I've just tested it again with the latest code from influxdb repository - it compiles fine and works with influxdb 0.13.
